[2024-10-01T08:46:11.592+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-01T08:46:11.602+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag.process_results.small_text.txt manual__2024-10-01T08:45:04.147022+00:00 [queued]>
[2024-10-01T08:46:11.606+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag.process_results.small_text.txt manual__2024-10-01T08:45:04.147022+00:00 [queued]>
[2024-10-01T08:46:11.606+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-01T08:46:11.612+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): process_results.small_text.txt> on 2024-10-01 08:45:04.147022+00:00
[2024-10-01T08:46:11.616+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=544) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-01T08:46:11.617+0000] {standard_task_runner.py:72} INFO - Started process 546 to run task
[2024-10-01T08:46:11.618+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'process_results.small_text.txt', 'manual__2024-10-01T08:45:04.147022+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmphl9fgp_f']
[2024-10-01T08:46:11.618+0000] {standard_task_runner.py:105} INFO - Job 72: Subtask process_results.small_text.txt
[2024-10-01T08:46:11.646+0000] {task_command.py:467} INFO - Running <TaskInstance: trigger_dag.process_results.small_text.txt manual__2024-10-01T08:45:04.147022+00:00 [running]> on host ff60ea0b688d
[2024-10-01T08:46:11.692+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trigger_dag' AIRFLOW_CTX_TASK_ID='process_results.small_text.txt' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T08:45:04.147022+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-01T08:45:04.147022+00:00'
[2024-10-01T08:46:11.694+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-01T08:46:11.694+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-01T08:46:11.694+0000] {logging_mixin.py:190} INFO - Current task name:process_results.small_text.txt state:running start_date:2024-10-01 08:46:11.602493+00:00
[2024-10-01T08:46:11.694+0000] {logging_mixin.py:190} INFO - Dag name:trigger_dag and current dag run status:running
[2024-10-01T08:46:11.694+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-01T08:46:11.695+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-01T08:46:11.695+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'rm /opt/airflow/data/small_text.txt']
[2024-10-01T08:46:11.700+0000] {subprocess.py:86} INFO - Output:
[2024-10-01T08:46:11.702+0000] {subprocess.py:93} INFO - rm: cannot remove '/opt/airflow/data/small_text.txt': No such file or directory
[2024-10-01T08:46:11.702+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-01T08:46:11.710+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-01T08:46:11.712+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-01T08:46:11.712+0000] {logging_mixin.py:190} INFO - Task start:2024-10-01 08:46:11.602493+00:00 end:2024-10-01 08:46:11.712178+00:00 duration:0.109685
[2024-10-01T08:46:11.712+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): process_results.small_text.txt> dag:<DAG: trigger_dag> dagrun:<DagRun trigger_dag @ 2024-10-01 08:45:04.147022+00:00: manual__2024-10-01T08:45:04.147022+00:00, state:running, queued_at: 2024-10-01 08:45:04.164484+00:00. externally triggered: True>
[2024-10-01T08:46:11.713+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2024-10-01T08:46:11.713+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=trigger_dag, task_id=process_results.small_text.txt, run_id=manual__2024-10-01T08:45:04.147022+00:00, execution_date=20241001T084504, start_date=20241001T084611, end_date=20241001T084611
[2024-10-01T08:46:11.719+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-01T08:46:11.720+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 72 for task process_results.small_text.txt (Bash command failed. The command returned a non-zero exit code 1.; 546)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-01T08:46:11.759+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-01T08:46:11.772+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-01T08:46:11.775+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
