[2024-10-11T11:10:44.019+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-11T11:10:44.030+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-10-11T11:10:42.571886+00:00 [queued]>
[2024-10-11T11:10:44.034+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-10-11T11:10:42.571886+00:00 [queued]>
[2024-10-11T11:10:44.034+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-11T11:10:44.040+0000] {taskinstance.py:2888} INFO - Executing <Task(SparkSubmitOperator): spark_count_number_of_accidents> on 2024-10-11 11:10:42.571886+00:00
[2024-10-11T11:10:44.043+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=343) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-11T11:10:44.044+0000] {standard_task_runner.py:72} INFO - Started process 352 to run task
[2024-10-11T11:10:44.044+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'count_accidents', 'spark_count_number_of_accidents', 'manual__2024-10-11T11:10:42.571886+00:00', '--job-id', '312', '--raw', '--subdir', 'DAGS_FOLDER/count_accidents_dag.py', '--cfg-path', '/tmp/tmp86mt9iw7']
[2024-10-11T11:10:44.045+0000] {standard_task_runner.py:105} INFO - Job 312: Subtask spark_count_number_of_accidents
[2024-10-11T11:10:44.075+0000] {task_command.py:467} INFO - Running <TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-10-11T11:10:42.571886+00:00 [running]> on host 14eb9bd36bc1
[2024-10-11T11:10:44.121+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='count_accidents' AIRFLOW_CTX_TASK_ID='spark_count_number_of_accidents' AIRFLOW_CTX_EXECUTION_DATE='2024-10-11T11:10:42.571886+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-11T11:10:42.571886+00:00'
[2024-10-11T11:10:44.123+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-11T11:10:44.123+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-11T11:10:44.123+0000] {logging_mixin.py:190} INFO - Current task name:spark_count_number_of_accidents state:running start_date:2024-10-11 11:10:44.030867+00:00
[2024-10-11T11:10:44.123+0000] {logging_mixin.py:190} INFO - Dag name:count_accidents and current dag run status:running
[2024-10-11T11:10:44.123+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-11T11:10:44.128+0000] {spark_submit.py:271} INFO - Could not load connection string spark, defaulting to yarn
[2024-10-11T11:10:44.130+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark ./spark/count_accidents.py
[2024-10-11T11:10:44.934+0000] {spark_submit.py:571} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-10-11T11:10:44.935+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2024-10-11T11:10:44.936+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2024-10-11T11:10:44.937+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2024-10-11T11:10:44.937+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2024-10-11T11:10:44.938+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2024-10-11T11:10:44.938+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2024-10-11T11:10:44.939+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2024-10-11T11:10:44.939+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-10-11T11:10:44.939+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-10-11T11:10:44.940+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-10-11T11:10:44.973+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark ./spark/count_accidents.py. Error code is: 1.
[2024-10-11T11:10:44.980+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-11T11:10:44.981+0000] {logging_mixin.py:190} INFO - Task start:2024-10-11 11:10:44.030867+00:00 end:2024-10-11 11:10:44.980218+00:00 duration:0.949351
[2024-10-11T11:10:44.982+0000] {logging_mixin.py:190} INFO - Task:<Task(SparkSubmitOperator): spark_count_number_of_accidents> dag:<DAG: count_accidents> dagrun:<DagRun count_accidents @ 2024-10-11 11:10:42.571886+00:00: manual__2024-10-11T11:10:42.571886+00:00, state:running, queued_at: 2024-10-11 11:10:42.583525+00:00. externally triggered: True>
[2024-10-11T11:10:44.982+0000] {logging_mixin.py:190} INFO - Failure caused by Cannot execute: spark-submit --master yarn --name arrow-spark ./spark/count_accidents.py. Error code is: 1.
[2024-10-11T11:10:44.982+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=count_accidents, task_id=spark_count_number_of_accidents, run_id=manual__2024-10-11T11:10:42.571886+00:00, execution_date=20241011T111042, start_date=20241011T111044, end_date=20241011T111044
[2024-10-11T11:10:45.000+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-11T11:10:45.001+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 312 for task spark_count_number_of_accidents (Cannot execute: spark-submit --master yarn --name arrow-spark ./spark/count_accidents.py. Error code is: 1.; 352)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark ./spark/count_accidents.py. Error code is: 1.
[2024-10-11T11:10:45.046+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-11T11:10:45.069+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-11T11:10:45.070+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
